### PR TITLE
Add custom nth calculations

### PR DESCRIPTION
**Pull request by ben-mulhern**
Geometric and arithmetic progressions both have simple formulas for calculating the nth item in a series, without having to iterate through the whole sequence to get there.

I have added an optional customNth parameter to createSequence, and implemented its use.

Apologies if coding style is not quite in sync with yours. I did turn on those useless semi colons though ;)

### CODE REVIEW

**Comment by ben-mulhern** [comment]
Oh and please feel free to point out any n00b mistakes that I've made - still in that phase where I'm probably making loads of noddy mistakes.

**Comment by ben-mulhern** [comment]
Also added the Collatz sequence (that we were discussing on FB a week or so ago).

**Comment by mikeyhogarth** [comment]
What do you want to do with this one? The API's changed since it was created so we can either batter it into a decent shape or we can close it and open a new one with the sequences you've done?

**Comment by ben-mulhern** [comment]
I'm not sure why sequence, arithmetic and geometric are even showing up in my PR anymore - it's just your changes, I've effectively not touched them.

**Pull request merged**
